os: osx

language: generic

env:
  matrix:
    - FORMULA_VERSION=
    - FORMULA_VERSION=--HEAD

matrix:
  allow_failures:
  - env: FORMULA_VERSION=--HEAD

rvm: system

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/travis/homebrew-fntsample
  - brew tap --repair
  - brew install --only-dependencies $FORMULA_VERSION fntsample

script:
  - brew install $FORMULA_VERSION --verbose fntsample
  - brew audit fntsample --strict
  - brew test fntsample
  - fntsample --help
